PT1-5108 Add support of kafka schema v3
ConnectedHomes/kafka-topic-monitor pull request #20
Opened 2022-04-20 16:42 UTC by tory-kk

2022-04-21 22:17 UTC, dimas requested changes

2022-04-21 22:17 UTC, dimas commented on lib/kafka_decoder.rb
> +      def initialize(protocol_type, generation, protocol, leader, current_state_timestamp = nil, members)
IMHO it would be just cleaner if you do not introduce a parameter with a default value **in the middle** of the parameter list but instead require to pass all parameters explicitly just passing `nil` for older schemas

2022-04-22 10:40 UTC, dimas approved these changes

2022-04-22 11:00 UTC, Illapikov approved these changes

2022-04-22 12:12 UTC, merged